spring:
  application:
    name: shop-eureka-server

server:
  port: 9000

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://user:password@localhost:9000/eureka/

security:
  basic:
    enabled: true
  user:
    name: user
    password: password